[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.0"
tag_format = "v$version"
version_files = [
    "app/__init__.py:version",
    "docker_build.sh:IMAGE_NAME",
    "pyproject.toml:version"
]